name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
          pip install pytest-cov==7.1.0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Python tests & coverage
        run: pytest tests/ --cov=. --cov-report=term --cov-report=html

      - name: Run js coverage
        run: |
          npx c8 --temp-directory .js_coverage report --reporter=text --reporter=html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: js-coverage-reports
          path: |
            coverage/
            htmlcov/